name: calendar_list
description: A new Flutter package.
version: 0.0.2
author: laiiihz
homepage: https://github.com/laiiihz/calendar_list

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lunar_calendar_converter: ^1.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

